#GET
GET http://localhost:8087/api/tutorParticular/formatoAula/
Content-Type: application/json
###

#GET
GET http://localhost:8087/api/tutorParticular/formatoAula/1
Content-Type: application/json
###

#POST
POST http://localhost:8087/api/tutorParticular/formatoAula/
Content-Type: application/json

{
    "nome": "Presencial",
    "descricao": "Não em casa",
    "idAdministrador": 1 
}
###

#PUT
PUT http://localhost:8087/api/tutorParticular/formatoAula/
Content-Type: application/json

{
    "idFormatoAula": 1,
    "nome": "Virtual I",
    "descricao": "Em casa I",
    "idAdministrador": 1
}
###

#DELETE
DELETE http://localhost:8087/api/tutorParticular/formatoAula/2
Content-Type: application/json
###